/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import method.Library;
import method.Loan;
import method.Member;
import method.Item;
import method.Book;
import method.Magazine;
/**
 *
 * @author ZALFAIL MUMTASA A
 */
public class FormPeminjamanBuku extends javax.swing.JFrame {
    private Library library;

    /**
     * Creates new form AddItem
     */
    public FormPeminjamanBuku(Library library) {
        this.library = library;   // Asosiasi di konstruktor
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1_IdBukuText = new javax.swing.JLabel();
        jLabel2_JudulBukuText = new javax.swing.JLabel();
        jTextField1_InputIdBuku = new javax.swing.JTextField();
        jTextField2_InputJudulBuku = new javax.swing.JTextField();
        jTextField3_InputIdAnggota = new javax.swing.JTextField();
        jTextField4_InputTanggalPinjam = new javax.swing.JTextField();
        jButton1_ButtonKirim = new javax.swing.JButton();
        jLabel5_IdAnggotaText = new javax.swing.JLabel();
        jLabel6_FormPeminjamanText = new javax.swing.JLabel();
        jLabel7_TanggalPinjamText = new javax.swing.JLabel();
        jLabel3_TanggalKembaliText = new javax.swing.JLabel();
        jTextField5_InputTanggalKembali = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1_IdBukuText.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel1_IdBukuText.setText("ID Buku/Majalah:");

        jLabel2_JudulBukuText.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel2_JudulBukuText.setText("Judul Buku/Majalah:");

        jTextField3_InputIdAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_InputIdAnggotaActionPerformed(evt);
            }
        });

        jButton1_ButtonKirim.setBackground(new java.awt.Color(0, 153, 255));
        jButton1_ButtonKirim.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_ButtonKirim.setText("Kirim");
        jButton1_ButtonKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_ButtonKirimMouseClicked(evt);
            }
        });

        jLabel5_IdAnggotaText.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel5_IdAnggotaText.setText("ID Anggota:");

        jLabel6_FormPeminjamanText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6_FormPeminjamanText.setText("Form Peminjaman");

        jLabel7_TanggalPinjamText.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel7_TanggalPinjamText.setText("Tanggal Peminjaman:");

        jLabel3_TanggalKembaliText.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel3_TanggalKembaliText.setText("Tanggal Pengembalian:");
        jLabel3_TanggalKembaliText.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5_IdAnggotaText)
                    .addComponent(jLabel2_JudulBukuText)
                    .addComponent(jLabel3_TanggalKembaliText)
                    .addComponent(jLabel7_TanggalPinjamText)
                    .addComponent(jLabel1_IdBukuText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1_InputIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3_InputIdAnggota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField4_InputTanggalPinjam)
                        .addComponent(jTextField5_InputTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField2_InputJudulBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel6_FormPeminjamanText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton1_ButtonKirim)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6_FormPeminjamanText)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5_IdAnggotaText)
                    .addComponent(jTextField3_InputIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_InputIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_IdBukuText))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_JudulBukuText)
                    .addComponent(jTextField2_InputJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3_TanggalKembaliText)
                            .addComponent(jTextField5_InputTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7_TanggalPinjamText)
                            .addComponent(jTextField4_InputTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1_ButtonKirim)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(421, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3_InputIdAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_InputIdAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_InputIdAnggotaActionPerformed

    private void jButton1_ButtonKirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_ButtonKirimMouseClicked
        // TODO add your handling code here:
        String memberId = jTextField3_InputIdAnggota.getText();
        String itemId = jTextField1_InputIdBuku.getText();
        String loanDate = jTextField4_InputTanggalPinjam.getText();

        Member member = library.findMemberById(memberId);
        Item item = library.findItemById(itemId);

        if (member == null || item == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Member atau Item tidak ditemukan.");
        } else if (item.isBorrowed()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Item ini sudah dipinjam.");
        }else {
           Loan loan = new Loan(); 
            loan.processLoan(member, item, loanDate);  // Proses peminjaman
            javax.swing.JOptionPane.showMessageDialog(this, "Peminjaman berhasil!");

            // Refresh ViewMember untuk melihat perubahan status
            new ViewMember(library).setVisible(true);
            this.dispose();
            }
    }//GEN-LAST:event_jButton1_ButtonKirimMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPeminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPeminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPeminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPeminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Library library = new Library();  // Inisialisasi Library
                library.addItem(new Book("101", "Java Programming for Beginners", "TechWorld Press", "John Smith"));
                library.addItem(new Book("102", "Advanced Python Techniques", "CodeMasters Publishing", "Sarah Johnson"));
                library.addItem(new Book("103", "The Art of Web Design", "Creative Design Books", "Emily Clark"));
                library.addItem(new Book("104", "Data Science from Scratch", "DataPro Books", "Michael Brown"));
                library.addItem(new Book("105", "Introduction to Algorithms", "MIT Press", "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest"));

                library.addItem(new Magazine("201", "Tech Innovators Monthly", "FutureTech Publications", "Daniel Harris"));
                library.addItem(new Magazine("202", "Design and Creativity", "Visionary Media", "Linda Green"));
                library.addItem(new Magazine("203", "The Business Insider", "BusinessWorld Publishing", "Robert Lee"));
                library.addItem(new Magazine("204", "Science Today", "Mary White", "Global Science Press"));
                library.addItem(new Magazine("205", "Creative Photography", "Photographers Press", "John Walker"));

                library.addMember(new Member("3001", "Aria", "Pelajar"));
                library.addMember(new Member("3002", "Zane", "Mahasiswa"));
                library.addMember(new Member("3003", "Elan", "Pelajar"));
                library.addMember(new Member("3004", "Rhea", "Pekerja"));
                library.addMember(new Member("3005", "Max", "Pekerja"));
                library.addMember(new Member("3006", "Rio", "Mahasiswa"));
                library.addMember(new Member("3007", "Kian", "Pelajar"));

                new FormPeminjamanBuku(library).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_ButtonKirim;
    private javax.swing.JLabel jLabel1_IdBukuText;
    private javax.swing.JLabel jLabel2_JudulBukuText;
    private javax.swing.JLabel jLabel3_TanggalKembaliText;
    private javax.swing.JLabel jLabel5_IdAnggotaText;
    private javax.swing.JLabel jLabel6_FormPeminjamanText;
    private javax.swing.JLabel jLabel7_TanggalPinjamText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1_InputIdBuku;
    private javax.swing.JTextField jTextField2_InputJudulBuku;
    private javax.swing.JTextField jTextField3_InputIdAnggota;
    private javax.swing.JTextField jTextField4_InputTanggalPinjam;
    private javax.swing.JTextField jTextField5_InputTanggalKembali;
    // End of variables declaration//GEN-END:variables
}
