/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import method.Admin;
/**
 *
 * @author ZALFAIL MUMTASA A
 */
public class Login extends javax.swing.JFrame {
    private Admin admin = new Admin("Ilzam", "12345"); // Composition, inisialisasi object di atribut

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
//        new Admin("Ilzam", "13579");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1_LoginText = new javax.swing.JLabel();
        jLabel2_UsernameText = new javax.swing.JLabel();
        jLabel3_PasswordText = new javax.swing.JLabel();
        jPasswordField1_PasswordInput = new javax.swing.JPasswordField();
        jTextField1_UsernameInput = new javax.swing.JTextField();
        jButton1_ButtonLogin = new javax.swing.JButton();
        jLabel1_GambarLogin = new javax.swing.JLabel();
        jLabel1_LoginText2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1_LoginText.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1_LoginText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_LoginText.setText("LOGIN ADMIN");

        jLabel2_UsernameText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2_UsernameText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_UsernameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2_UsernameText.setText("Username");

        jLabel3_PasswordText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3_PasswordText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_PasswordText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3_PasswordText.setText("Password");

        jPasswordField1_PasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1_PasswordInputActionPerformed(evt);
            }
        });

        jTextField1_UsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_UsernameInputActionPerformed(evt);
            }
        });

        jButton1_ButtonLogin.setBackground(new java.awt.Color(0, 153, 255));
        jButton1_ButtonLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton1_ButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_ButtonLogin.setText("Login");
        jButton1_ButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_ButtonLoginMouseClicked(evt);
            }
        });

        jLabel1_GambarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/login-removebg-preview.png"))); // NOI18N

        jLabel1_LoginText2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1_LoginText2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_LoginText2.setText("Silakan login sebagai Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1_GambarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2_UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1_UsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3_PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1_ButtonLogin)
                                    .addComponent(jPasswordField1_PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1_LoginText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1_LoginText2)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1_LoginText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_LoginText2)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_UsernameText)
                    .addComponent(jTextField1_UsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_PasswordText)
                    .addComponent(jPasswordField1_PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton1_ButtonLogin)
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1_GambarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 910, 500);

        setSize(new java.awt.Dimension(920, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1_PasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1_PasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1_PasswordInputActionPerformed

    private void jButton1_ButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_ButtonLoginMouseClicked
        // TODO add your handling code here:
        String username = jTextField1_UsernameInput.getText();
        String password = new String(jPasswordField1_PasswordInput.getPassword());

        if (admin.login(username, password)) {
            // Kalo login berhasil, trus lanjut Main Menu
            new MainMenu().setVisible(true);
            this.dispose();
        } else {
            // Kalo gagal, ada pesan error
            javax.swing.JOptionPane.showMessageDialog(this, "Login Gagal! Periksa username dan password.");
        }
    }//GEN-LAST:event_jButton1_ButtonLoginMouseClicked

    private void jTextField1_UsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_UsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_UsernameInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_ButtonLogin;
    private javax.swing.JLabel jLabel1_GambarLogin;
    private javax.swing.JLabel jLabel1_LoginText;
    private javax.swing.JLabel jLabel1_LoginText2;
    private javax.swing.JLabel jLabel2_UsernameText;
    private javax.swing.JLabel jLabel3_PasswordText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1_PasswordInput;
    private javax.swing.JTextField jTextField1_UsernameInput;
    // End of variables declaration//GEN-END:variables
}
