/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import method.Library;
import method.Book;
import method.Member;
import method.Magazine;
/**
 *
 * @author ZALFAIL MUMTASA A
 */
public class MainMenu extends javax.swing.JFrame {
    private Library library = new Library();  // Inisialisasi object di atribut >>> composition

    /**
     * Creates new form home
     */
    public MainMenu() {
        initLibrary();
        initComponents();
    }
    
    // Initialize library with items and members (buku, anggota)
    public void initLibrary() {
        library.addItem(new Book("101", "Java Programming for Beginners", "TechWorld Press", "John Smith"));
        library.addItem(new Book("102", "Advanced Python Techniques", "CodeMasters Publishing", "Sarah Johnson"));
        library.addItem(new Book("103", "The Art of Web Design", "Creative Design Books", "Emily Clark"));
        library.addItem(new Book("104", "Data Science from Scratch", "DataPro Books", "Michael Brown"));
        library.addItem(new Book("105", "Introduction to Algorithms", "MIT Press", "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest"));
        
        library.addItem(new Magazine("201", "Tech Innovators Monthly", "FutureTech Publications", "Daniel Harris"));
        library.addItem(new Magazine("202", "Design and Creativity", "Visionary Media", "Linda Green"));
        library.addItem(new Magazine("203", "The Business Insider", "BusinessWorld Publishing", "Robert Lee"));
        library.addItem(new Magazine("204", "Science Today", "Mary White", "Global Science Press"));
        library.addItem(new Magazine("205", "Creative Photography", "Photographers Press", "John Walker"));

        library.addMember(new Member("3001", "Aria", "Pelajar"));
        library.addMember(new Member("3002", "Zane", "Mahasiswa"));
        library.addMember(new Member("3003", "Elan", "Pelajar"));
        library.addMember(new Member("3004", "Rhea", "Pekerja"));
        library.addMember(new Member("3005", "Max", "Pekerja"));
        library.addMember(new Member("3006", "Rio", "Mahasiswa"));
        library.addMember(new Member("3007", "Kian", "Pelajar"));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_MenuUtamaText = new javax.swing.JPanel();
        jButton3_ButtonPinjamBuku = new javax.swing.JButton();
        jButton1_ButtonLihatBuku = new javax.swing.JButton();
        jLabel1_LihatItemText = new javax.swing.JLabel();
        jLabel5_PinjamBukuText = new javax.swing.JLabel();
        jLabel2_DaftarAnggotaText = new javax.swing.JLabel();
        jButton4_ButtonLihatAnggota = new javax.swing.JButton();
        jLabel3_MenuUtamaText = new javax.swing.JLabel();
        jButton2_ButtonKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1_SelamatDatangText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setMinimumSize(new java.awt.Dimension(910, 500));
        setPreferredSize(new java.awt.Dimension(910, 500));

        jPanel1_MenuUtamaText.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1_MenuUtamaText.setForeground(new java.awt.Color(255, 255, 255));

        jButton3_ButtonPinjamBuku.setBackground(new java.awt.Color(0, 153, 255));
        jButton3_ButtonPinjamBuku.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_ButtonPinjamBuku.setText("Pinjam Buku");
        jButton3_ButtonPinjamBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_ButtonPinjamBukuMouseClicked(evt);
            }
        });
        jButton3_ButtonPinjamBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_ButtonPinjamBukuActionPerformed(evt);
            }
        });

        jButton1_ButtonLihatBuku.setBackground(new java.awt.Color(0, 153, 255));
        jButton1_ButtonLihatBuku.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_ButtonLihatBuku.setText("Lihat Item");
        jButton1_ButtonLihatBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_ButtonLihatBukuMouseClicked(evt);
            }
        });
        jButton1_ButtonLihatBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ButtonLihatBukuActionPerformed(evt);
            }
        });

        jLabel1_LihatItemText.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1_LihatItemText.setText("Daftar Buku dan Majalah");

        jLabel5_PinjamBukuText.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5_PinjamBukuText.setText("Peminjaman Buku");

        jLabel2_DaftarAnggotaText.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2_DaftarAnggotaText.setText("Daftar Anggota");

        jButton4_ButtonLihatAnggota.setBackground(new java.awt.Color(0, 153, 255));
        jButton4_ButtonLihatAnggota.setForeground(new java.awt.Color(255, 255, 255));
        jButton4_ButtonLihatAnggota.setText("Lihat Anggota");
        jButton4_ButtonLihatAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4_ButtonLihatAnggotaMouseClicked(evt);
            }
        });
        jButton4_ButtonLihatAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_ButtonLihatAnggotaActionPerformed(evt);
            }
        });

        jLabel3_MenuUtamaText.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3_MenuUtamaText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_MenuUtamaText.setText("Menu Utama");

        jButton2_ButtonKeluar.setBackground(new java.awt.Color(0, 153, 255));
        jButton2_ButtonKeluar.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_ButtonKeluar.setText("Keluar");
        jButton2_ButtonKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_ButtonKeluarMouseClicked(evt);
            }
        });
        jButton2_ButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_ButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_MenuUtamaTextLayout = new javax.swing.GroupLayout(jPanel1_MenuUtamaText);
        jPanel1_MenuUtamaText.setLayout(jPanel1_MenuUtamaTextLayout);
        jPanel1_MenuUtamaTextLayout.setHorizontalGroup(
            jPanel1_MenuUtamaTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_MenuUtamaTextLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel1_MenuUtamaTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5_PinjamBukuText)
                    .addComponent(jLabel2_DaftarAnggotaText)
                    .addComponent(jLabel1_LihatItemText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1_MenuUtamaTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4_ButtonLihatAnggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jButton1_ButtonLihatBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3_ButtonPinjamBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(196, 196, 196))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_MenuUtamaTextLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1_MenuUtamaTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_MenuUtamaTextLayout.createSequentialGroup()
                        .addComponent(jLabel3_MenuUtamaText)
                        .addGap(414, 414, 414))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_MenuUtamaTextLayout.createSequentialGroup()
                        .addComponent(jButton2_ButtonKeluar)
                        .addGap(43, 43, 43))))
        );
        jPanel1_MenuUtamaTextLayout.setVerticalGroup(
            jPanel1_MenuUtamaTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_MenuUtamaTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3_MenuUtamaText)
                .addGap(60, 60, 60)
                .addGroup(jPanel1_MenuUtamaTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_LihatItemText)
                    .addComponent(jButton1_ButtonLihatBuku))
                .addGap(61, 61, 61)
                .addGroup(jPanel1_MenuUtamaTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_DaftarAnggotaText)
                    .addComponent(jButton4_ButtonLihatAnggota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel1_MenuUtamaTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5_PinjamBukuText)
                    .addComponent(jButton3_ButtonPinjamBuku))
                .addGap(27, 27, 27)
                .addComponent(jButton2_ButtonKeluar)
                .addGap(39, 39, 39))
        );

        jPanel2.setBackground(new java.awt.Color(243, 175, 175));

        jLabel1_SelamatDatangText.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1_SelamatDatangText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_SelamatDatangText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_SelamatDatangText.setText("Selamat Datang di Perpustakaan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(jLabel1_SelamatDatangText, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1_SelamatDatangText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_MenuUtamaText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1_MenuUtamaText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(926, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_ButtonLihatBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ButtonLihatBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_ButtonLihatBukuActionPerformed

    private void jButton3_ButtonPinjamBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_ButtonPinjamBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_ButtonPinjamBukuActionPerformed

    private void jButton2_ButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_ButtonKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_ButtonKeluarActionPerformed

    private void jButton3_ButtonPinjamBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_ButtonPinjamBukuMouseClicked
        // TODO add your handling code here:
        new FormPeminjamanBuku(library).setVisible(true);  // Open the loan form
        this.dispose();  // Close Main Menu
    }//GEN-LAST:event_jButton3_ButtonPinjamBukuMouseClicked

    private void jButton4_ButtonLihatAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_ButtonLihatAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4_ButtonLihatAnggotaActionPerformed

    private void jButton4_ButtonLihatAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_ButtonLihatAnggotaMouseClicked
        // TODO add your handling code here:
        new ViewMember(library).setVisible(true);  // Kirim library ke ViewMember
        this.dispose(); // Tutup MainMenu
    }//GEN-LAST:event_jButton4_ButtonLihatAnggotaMouseClicked

    private void jButton1_ButtonLihatBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_ButtonLihatBukuMouseClicked
        // TODO add your handling code here:
        new ViewItem(library).setVisible(true); // Kirim library ke ViewItem
        this.dispose(); // Tutup MainMenu
    }//GEN-LAST:event_jButton1_ButtonLihatBukuMouseClicked

    private void jButton2_ButtonKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_ButtonKeluarMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);  // Kembali ke halaman login
        this.dispose(); // Tutup MainMenu
    }//GEN-LAST:event_jButton2_ButtonKeluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_ButtonLihatBuku;
    private javax.swing.JButton jButton2_ButtonKeluar;
    private javax.swing.JButton jButton3_ButtonPinjamBuku;
    private javax.swing.JButton jButton4_ButtonLihatAnggota;
    private javax.swing.JLabel jLabel1_LihatItemText;
    private javax.swing.JLabel jLabel1_SelamatDatangText;
    private javax.swing.JLabel jLabel2_DaftarAnggotaText;
    private javax.swing.JLabel jLabel3_MenuUtamaText;
    private javax.swing.JLabel jLabel5_PinjamBukuText;
    private javax.swing.JPanel jPanel1_MenuUtamaText;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
